### ISSUE TITLE
Allow participants to be added and removed from list of participants

### ISSUE THREAD

**Issue by mannenen** [SickJumpsSoftware/RollInish#4]

**Comment by zatoseyes** [comment]
I think this will be best as a pop-up. User clicks File > New. or a big "New Encounter" button and this thing pops up. You do the set-up for the encounter, adding creatures and heroes and then click "Done" and it loads it all into the main window and Big List.

So I originally envisioned a GUI I have seen in other applications, but don't know the name for. Basically you have two parallel lists. One has stuff in it (in this case creatures.JSON saved to the disk and in the right folder path) and the other needs stuff to be used at all (in this case the list of creatures in the encounter [Not the Big List tm.])

I think instead of just showing a file structure it would be neater to have tabs over the "Available" list for each sub-folder of the right folder path, call it Creatures or whatever.

Then you just tab around and select the creatures you want. They get moved over to the encounter list and we do the roll initiative thing you suggested in #6. There would also be a button here to automatically add the heroes.JSON present in the "Heroes" folder. I think being able to set that folder/file path would be handy if you're running multiple campaigns.

**Comment by mannenen** [comment]
This issue is implemented in PR #10
